version: '3.5'

volumes:
    wordpress:
       driver: local
       driver_opts:
         type: none
         o: bind
         device: /home/adpachec/data/wordpress

    mariadb:
       driver: local
       driver_opts:
         type: none
         o: bind
         device: /home/adpachec/data/mariadb

networks:
  inception:
    driver: bridge

services:
    mariadb:
       container_name: mariadb
       build: ./requirements/mariadb
        env_file:
         - .env
       volumes:
         - mariadb:/var/lib/mysql
       networks:
         - inception
       restart: always

    wordpress:
       container_name: wordpress
       build: ./requirements/wordpress
       depends_on:
         - mariadb
        env_file:
         - .env
       volumes:
         - wordpress:/var/www/html
       networks:
         - inception
       restart: always

    nginx:
       container_name: nginx
       build: ./requirements/nginx
       depends_on:
         - wordpress
       volumes:
         - wordpress:/var/www/html
       ports:
         - "443:443"
       networks:
         - inception
       restart: always


