version: '3.5'

volumes:
  wordpress:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/adpachec/data/wordpress

  mariadb:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/adpachec/data/mariadb

services:
  nginx:
    container_name: nginx
    build: ./requirements/nginx
    depends_on:
      - wordpress
    ports:
      - "443:443"
    volumes:
      - wordpress:/var/www/html
    networks:
      - inception
    restart: always

  mariadb:
    container_name: mariadb
    build: ./requirements/mariadb
    volumes:
      - mariadb:/var/lib/mysql
    networks:
      - inception
    restart: always
    env_file:
      - .env

  wordpress:
    container_name: wordpress
    build: 
      context: ./requirements/wordpress
      dockerfile: Dockerfile
    depends_on:
      - mariadb
    volumes:
      - wordpress:/var/www/html
    networks:
      - inception
    restart: always

networks:
  inception:
    driver: bridge