version: '3.8'

services:
  nginx:
    container_name: nginx
    build: ./requirements/nginx
    ports:
      - 443:443
    volumes:
      - wordpressVol:/var/www/html
    restart: always
    networks:
      - inception

  mariadb:
    container_name: mariadb
    build: ./requirements/mariadb
    volumes:
      - mariadbVol:/var/lib/mysql
    networks:
      - inception
    restart: always
    env_file:
      - .env

  wordpress:
    container_name: wordpress
    depends_on:
      - mariadb
    build:
      context: ./requirements/wordpress
      dockerfile: Dockerfile
    restart: always
    env_file:
      - .env
    volumes:
      - wordpressVol:/var/www/html
    networks:
      - inception

volumes:
  mariadbVol:
    driver: local
    driver_opts:
      type: none
      device: /home/adpachec/data/mariadb
      o: bind
  wordpressVol:
    driver: local
    driver_opts:
      type: none
      device: /home/adpachec/data/wordpress
      o: bind

networks:
  inception:
    driver: bridge