version:  '3.8'
services:
    nginx:
      depends_on:
        - wordpress
      container_name: nginx
      build: ./requirements/nginx
      volumes:
        - "wordpress-vol:/var/www/html"
      ports:
        - "443:443"
      networks:
        - inception
      restart: always
    wordpress:
      depends_on:
        - mariadb
      container_name: wordpress
      build: ./requirements/wordpress
      env_file:
        - .env
      networks:
        - inception
      volumes:
        - "wordpress-vol:/var/www/html"
      restart: always
    mariadb:
          container_name: mariadb
          env_file:
            - .env
          build: ./requirements/mariadb
          networks:
            - inception
          volumes:
            - "mariadb-vol:/var/lib/mysql"
          restart: always
volumes:
  mariadb-vol:
    driver: local
    driver_opts:
      type: none
      device: /home/adpachec/data/mariadb
      o: bind
  wordpress-vol:
    driver: local
    driver_opts:
      type: none
      device: /home/adpachec/data/wordpress
      o: bind
networks:
  inception:
    driver: bridge
