version: '3.5'

volumes:
    wordpress:
       driver: local
       driver_opts:
         type: none
         o: bind
         device: /home/adpachec/data/wordpress

    mariadb:
       driver: local
       driver_opts:
         type: none
         o: bind
         device: /home/adpachec/data/mariadb

networks:
  inception:
    driver: bridge

services:
    nginx:
       container_name: nginx
       build: ./requirements/nginx
       depends_on:
         - wordpress
       volumes:
         - wordpress:/var/www/html
       ports:
         - "443:443"
       networks:
         - inception
       restart: always

    wordpress:
       container_name: wordpress
       build: ./requirements/wordpress
       depends_on:
         - mariadb
       environment:
         MYSQL_HOST: ${WP_HOST_NAME}
         WP_DB_NAME: ${WP_DB_NAME}
         WP_DB_USER: ${WP_DB_USER}
         WP_DB_PASSWORD: ${WP_DB_PASSWORD}
         WP_DB_HOST: ${WP_DB_HOST}
       volumes:
         - wordpress:/var/www/html
       networks:
         - inception
       restart: always

    mariadb:
       container_name: mariadb
       build: ./requirements/mariadb
       environment:
         MYSQL_ROOT_PASSWORD: ${ROOT_DB_PASS}
         WP_DB_NAME: ${WP_DB_NAME}
         WP_DB_USER: ${WP_DB_USER}
         WP_DB_PASSWORD: ${WP_DB_PASSWORD}
       volumes:
         - mariadb:/var/lib/mysql
       networks:
         - inception
       restart: always
