version: '3'

services:
    nginx:
       container_name: nginx
       build: ./srcs/nginx
       volumes:
         - wordpress_files:/var/www/html
       ports:
         - "443:443"
       networks:
         - inception
       restart: always

    wordpress:
       container_name: wordpress
       build: ./srcs/wordpress
       environment:
         WP_DB_NAME: ${WP_DB_NAME}
         WP_DB_USER: ${WP_DB_USER}
         WP_DB_PASSWORD: ${WP_DB_PASSWORD}
         WP_DB_HOST: ${WP_DB_HOST}
         AUTH_KEY: ${AUTH_KEY}
         SECURE_AUTH_KEY: ${SECURE_AUTH_KEY}
         LOGGED_IN_KEY: ${LOGGED_IN_KEY}
         NONCE_KEY: ${NONCE_KEY}
         AUTH_SALT: ${AUTH_SALT}
         SECURE_AUTH_SALT: ${SECURE_AUTH_SALT}
         LOGGED_IN_SALT: ${LOGGED_IN_SALT}
         NONCE_SALT: ${NONCE_SALT}
       volumes:
         - wordpress:/var/www/html
       networks:
         - inception
       restart: always

    mariadb:
       build: ./srcs/mariadb
       environment:
         MYSQL_ROOT_PASSWORD: ${ROOT_PASSWORD}
         MYSQL_DATABASE: ${WP_DB_NAME}
         MYSQL_USER: ${WP_DB_USER}
         MYSQL_PASSWORD: ${WP_DB_PASSWORD}
       volumes:
         - mariadb:/var/lib/mysql
         - .init.sql:/docker-entrypoint-initdb.d/init.sql
       networks:
         - inception
       restart: always

networks:
  inception:
    driver: bridge

volumes:
    wordpress_files:
       driver: local
       driver_opts:
         type: none
         o: bind
         device: /home/adpachec/data/wordpress

    mariadb_data:
       driver: local
       driver_opts:
         type: none
         o: bind
         device: /home/adpachec/data/mariadb
